import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ['100','200','300','400','500','600','700','800','900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "SIXTEEN CLOTHING",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" className="scrollbar scrollbar-thumb-mainBlack/90 scrollbar-track-mainBlack/50 ">
      <body className={`${poppins.className} `} >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
